Fix gem building error
Building the gem would give this errror:

	$ rake build
	rake aborted!
	WARNING:  See http://guides.rubygems.org/specification-reference/ for help
	ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    	["OnlineCheckout", "V2.0.pdf", "docs/C2B"] are not files

This is because the line separator configuration was splitting files
like this:

	"docs/C2B",
	"OnlineCheckout",
	"V2.0.pdf",
	"docs/processCheckOutRequest.xml"

Instead of like this:

	"docs/C2B OnlineCheckout V2.0.pdf",
    "docs/processCheckOutRequest.xml",